# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  version: '0.0.8-alpha'

steps:
  - task: UseDotNet@2
    displayName: 'Use .net core 3.1'
    inputs:
      version: '3.1.x'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Make NUGET package'
    inputs:
      command: pack
      versioningScheme: byEnvVar
      packagesToPack: '**/HassClient.csproj'
      outputDir: '$(Build.ArtifactStagingDirectory)/NUGET'
      versionEnvVar: version

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'